#!/bin/bash


IOPRO_INCLUDE_PATH=$HOME/anaconda/envs/iopro-test-np1.7/include/python2.7

WHERE="$HOME/dependencies/"

function mk_depend_path()
{
    echo $WHERE$1
}

if [ ! -d $(mk_depend_path '') ]; then
    mkdir $(mk_depend_path '')
fi

pushd $(mk_depend_path '') >/dev/null


# get a unixODBC driver manager
if [ ! -d unixODBC-2.3.1 ]; then
    if [ ! -f unixODBC-2.3.1.tar.gz ]; then
	wget ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.1.tar.gz
    fi

    tar -zxvf unixODBC-2.3.1.tar.gz
    pushd unixODBC-2.3.1 >/dev/null
    ./configure
    make
    popd >/dev/null
fi

if [ -f unixODBC-2.3.1.tar.gz ]; then
    # leave it clean
    rm unixODBC-2.3.1.tar.gz
fi


IOPRO_INCLUDE_PATH=$(mk_depend_path unixODBC-2.3.1):$IOPRO_INCLUDE_PATH
IOPRO_INCLUDE_PATH=$(mk_depend_path unixODBC-2.3.1/include):$IOPRO_INCLUDE_PATH
export IOPRO_INCLUDE_PATH

echo 'IOPRO_INCLUDE_PATH=' $IOPRO_INCLUDE_PATH

IOPRO_LIBRARY_PATH=$(mk_depend_path unixODBC-2.3.1):$IOPRO_LIBRARY_PATH
export IOPRO_LIBRARY_PATH

echo 'IOPRO_LIBRARY_PATH=' $IOPRO_LIBRARY_PATH

LD_LIBRARY_PATH=$(mk_depend_path unixODBC-2.3.1/DriverManager/.libs):$LD_LIBRARY_PATH
export LD_LIBRARY_PATH

echo 'LD_LIBRARY_PATH=' $LD_LIBRARY_PATH

popd >/dev/null

printf '\n\nBuilding...\n'
python setup.py build_ext --inplace --include-dirs=$IOPRO_INCLUDE_PATH --library-dirs=$IOPRO_LIBRARY_PATH || exit 1

exit


